
# This is an example neoforge.mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:
# https://github.com/neoforged/NeoForge/blob/main/src/main/resources/META-INF/neoforge.mods.toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"

# A version range to match for said mod loader
loaderVersion="${loader_version_range}"

# The license for your mod
license="${mod_license}"

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

# A list of mods
[[mods]]

# The modid of the mod
modId="${mod_id}"

# The version number of the mod
version="${mod_version}"

# A display name for the mod
displayName="${mod_name}"

# A URL to query for updates for this mod
#updateJSONURL="https://change.me.example.invalid/updates.json"

# A URL for the homepage for this mod
displayURL="https://github.com/modziE3/Scary-Water-MC-Mod"

# A file name in the root of the mod JAR containing a logo
logoFile="logo.png"

# A text field displayed in the mod UI
#credits=""

# The authors of the mod
authors="Modzyyy"

# The description text for the mod
description='''
Makes water scarier with realism!
'''

# The mixin configuration
[[mixins]]
config="${mod_id}.mixins.json"

# Access transformers
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"


[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
version = "[21.1.100,)"
ordering = "NONE"
side = "BOTH"

# Features
#[features.${mod_id}]
#openGLVersion="[3.2,)"
